name: Weekly Movie Update
on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

- name: Commit and push changes
        run: |
          git config --global user.name 'Movie Bot'
          git config --global user.email 'bot@github.com'
          git add .  # Questo aggiunge sia index.html che events_list.txt
          git commit -m "Weekly automated movie update" || exit 0
          git push